version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: arslan-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student_pass
      POSTGRES_DB: Arslan
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: arslan-flask-app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=Arslan
      - DB_USER=student
      - DB_PASS=student_pass
    volumes:
      - .:/app

volumes:
  db_data:
